#!/bin/sh
SERVICE=/usr/sbin/service
LOGGER=/usr/bin/logger

while true; do
        ${SERVICE} masterNugget status > /dev/null
        ret=$?
        if [ $ret -ne 0 ]; then
                ${LOGGER} -p local7.notice -t masterNugget_safed Restarted masterNugget
                ${SERVICE} masterNugget start > /dev/null 2>&1
        fi
        sleep 10
done
