#!/bin/sh
SERVICE=/usr/sbin/service
LOGGER=/usr/bin/logger

while true; do
        ${SERVICE} dispatcher status > /dev/null
        ret=$?
        if [ $ret -ne 0 ]; then
                ${LOGGER} -p local7.notice -t dispatcher_safed Restarted dispatcher
                ${SERVICE} dispatcher start > /dev/null 2>&1
        fi
        sleep 10
done
