# SQLite version 3.x
#   gem install sqlite3-ruby (not necessary on OS X Leopard)
development:
  adapter: mysql
  database: razorback
  pool: 5
  timeout: 5000
  username: razorback
  password: razorback
  host: desktop

production:
  adapter: mysql
  database: razorback
  pool: 5
  timeout: 5000
  username: razorback
  password: razorback
  host: desktop
