NUGGET_INCLUDES='-I$(top_srcdir)/src'
NUGGET_LIBRARIES='$(RAZORBACK_LIBS)'

AC_SUBST(NUGGET_INCLUDES)
AC_SUBST(NUGGET_LIBRARIES)
AC_SUBST(NUGGET_VERSION)
AC_SUBST(extra_incl)
AC_SUBST(XCCFLAGS)
AS_AC_EXPAND(PKGLIBDIR, "${libdir}/razorback")

