#include "foxdebug.h"

/**This maintains a list of the printable string-equivalents of the PDFTokenType enum values
 * Used by the printToken function for debugging purposes.
 */
const char *PDFTokenString[] = {"ERROR", "ARRAY", "BINHEAD", "COMMENT", "CLOSEANGLE", "CLOSEARRAY", "CLOSEDICT", "CLOSEPAREN", "DECIMAL", "DICTIONARY", "END", "ENDOBJ", "ENDSTREAM", "IDENT", "MINUS", "NAME", "NAME_STRMLEN", "FILTER", "FILTER_HEXDECODE", "FILTER_85DECODE", "FILTER_LZWDECODE", "FILTER_FLATEDECODE", "FILTER_RLEDECODE", "FILTER_CCITTDECODE", "FILTER_JBIG2DECODE", "FILTER_DCTDECODE", "FILTER_JPXDECODE", "FILTER_CRYPTDECODE", "NEWLINE", "HEXSTRING", "INTEGER", "LITSTRING", "REAL", "NULLOBJ", "OBJ", "OPENANGLE", "OPENARRAY", "OPENDICT", "OPENPAREN", "PDFVERS", "PLUS", "REF", "STARTXREF", "STREAM", "STREAMCONTENT", "TRAILER", "XREF", "TRUE", "FALSE", "ENDOFFILE", "NAME_SUBTYPE", "NAME_S", "NAME_JAVASCRIPT", "NAME_JS", "NAME_TRUETYPE", "NAME_OPENTYPE", "NAME_DECODEPARAMS", "NAME_URI", "NAME_DCPRMS_COLUMNS", "NAME_DCPRMS_BPC", "NAME_DCPRMS_COLORS", "NAME_DCPRMS_PREDICTOR"};

/**Simple print PDFTokenType function
 */
void printToken(PDFTokenType type) {
	printf("%s\n", PDFTokenString[type]);
}
